FROM php:8.3-cli-alpine

RUN apk add --no-cache git unzip postgresql-dev oniguruma-dev libzip-dev icu-dev \
    && docker-php-ext-install pdo pdo_pgsql bcmath intl zip pcntl

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
