/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments.$slug'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppAdminTournamentsCreateRouteImport } from './routes/_app.admin.tournaments.create'
import { Route as AppAdminTournamentsSlugEditRouteImport } from './routes/_app.admin.tournaments.$slug.edit'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TournamentsRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTournamentsCreateRoute =
  AppAdminTournamentsCreateRouteImport.update({
    id: '/admin/tournaments/create',
    path: '/admin/tournaments/create',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminTournamentsSlugEditRoute =
  AppAdminTournamentsSlugEditRouteImport.update({
    id: '/admin/tournaments/$slug/edit',
    path: '/admin/tournaments/$slug/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/tournaments/create': typeof AppAdminTournamentsCreateRoute
  '/admin/tournaments/$slug/edit': typeof AppAdminTournamentsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/tournaments/create': typeof AppAdminTournamentsCreateRoute
  '/admin/tournaments/$slug/edit': typeof AppAdminTournamentsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/_app/admin/tournaments/create': typeof AppAdminTournamentsCreateRoute
  '/_app/admin/tournaments/$slug/edit': typeof AppAdminTournamentsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tournaments'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/tournaments/$slug'
    | '/admin/tournaments/create'
    | '/admin/tournaments/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tournaments'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/tournaments/$slug'
    | '/admin/tournaments/create'
    | '/admin/tournaments/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/tournaments'
    | '/_app/profile'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/tournaments/$slug'
    | '/_app/admin/tournaments/create'
    | '/_app/admin/tournaments/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  TournamentsRoute: typeof TournamentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tournaments/create': {
      id: '/_app/admin/tournaments/create'
      path: '/admin/tournaments/create'
      fullPath: '/admin/tournaments/create'
      preLoaderRoute: typeof AppAdminTournamentsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tournaments/$slug/edit': {
      id: '/_app/admin/tournaments/$slug/edit'
      path: '/admin/tournaments/$slug/edit'
      fullPath: '/admin/tournaments/$slug/edit'
      preLoaderRoute: typeof AppAdminTournamentsSlugEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppAdminTournamentsCreateRoute: typeof AppAdminTournamentsCreateRoute
  AppAdminTournamentsSlugEditRoute: typeof AppAdminTournamentsSlugEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppAdminTournamentsCreateRoute: AppAdminTournamentsCreateRoute,
  AppAdminTournamentsSlugEditRoute: AppAdminTournamentsSlugEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TournamentsRouteChildren {
  TournamentsSlugRoute: typeof TournamentsSlugRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsSlugRoute: TournamentsSlugRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  TournamentsRoute: TournamentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
